name: Local Config
version: 1.0.0
schema: v1

models:
  - name: Local Qwen
    provider: ollama
    model: qwen2.5-coder:1.5b
    roles:
      - chat
      - edit
      - apply

defaultCompletionOptions:
  contextLength: 8192
  maxTokens: 512