services:
  llama:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: llama-server
    ports:
      - "8080:8080"
    volumes:
      - ./models:/models
    command: >
      -m /models/Qwen3-8B-Q4_K_M.gguf
      --host 0.0.0.0
      --port 8080
      -t 5
      -c 4096
      -b 512
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    depends_on:
      - llama
    ports:
      - "3000:8080"
    environment:
      OLLAMA_BASE_URL: ''
      OPENAI_API_BASE_URL: http://llama:8080/v1
      OPENAI_API_KEY: not-needed
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped

  openai-edge-tts:
    image: travisvn/openai-edge-tts:latest
    container_name: openai-edge-tts
    environment:
      REQUIRE_API_KEY: "False"
    ports:
      - "5050:5050"
    restart: unless-stopped

  faster-whisper:
    image: ghcr.io/speaches-ai/speaches:latest-cpu
    container_name: faster-whisper
    ports:
      - "8000:8000"
    volumes:
      - hf-hub-cache:/home/ubuntu/.cache/huggingface/hub
    restart: unless-stopped

volumes:
  hf-hub-cache:
  open-webui: